[package]
name    = "dwm1001"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]


[dependencies]
cortex-m    = "0.5.4"
cortex-m-rt = "0.5.1"
# This is my fork of nrf52-hal. I'm depending on it for the time being, until
# work on it has settled down a bit.
nrf52-hal   = { git = "https://github.com/braun-robotics/nrf52-hal.git" }

[dev-dependencies]
nb = "0.1.1"

[features]
rt = ["nrf52-hal/rt"]


[[example]]
name              = "blink"
required-features = ["rt"]


[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
